apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-helm-applicationset-git-generators-ironman
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/nopponcha/argocd-demo.git
              revision: HEAD
              directories:
                - path: argo-cd/helm-value/ironman/*/*
          - list:
              elements:
              #DEV
                - env: dev
                  cluster: "https://kubernetes.default.svc"
                  clustername: minikube

            selector:
              matchExpressions:
                - key: "env"
                  operator: In
                  values:
                    - dev         
  template:
    metadata:
      name: "{{path[2]}}-{{path[3]}}-{{clustername}}-{{env}}"  # เช่น app-be-dev-minikube
    spec:
      project: default
      sources:
        - repoURL: https://github.com/nopponcha/helm-chart.git
          targetRevision: HEAD
          path: argo-cd/charts
          helm:
            valueFiles:
              - "$values/argo-cd/helm-value/ironman/{{path[3]}}/{{env}}/values.yaml"
        - repoURL: https://github.com/nopponcha/argocd-demo.git
          targetRevision: HEAD
          ref: values
      destination:
        server: "{{cluster}}"
        namespace: "{{path[2]}}-{{env}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - DisableHelmChartCache=true
          
