apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-helm-applicationset-git-generators-scbconnect
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - git:
        repoURL: https://github.com/nopponcha/argocd-demo.git
        revision: main
        directories:
          - path: helm-value/scbconnect/*/*
  template:
    metadata:
      name: "{{path[2]}}-{{path.basename}}"
    spec:
      project: default
      sources:
      - repoURL: https://github.com/nopponcha/helm-chart.git
        targetRevision: main
        path: charts
        helm:
          valueFiles:
            - "$values/helm-value/scbconnect/{{path[2]}}/{{path.basename}}/values.yaml"   
      - repoURL: https://github.com/nopponcha/argocd-demo.git
        targetRevision: main
        ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true        