apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-helm-applicationset-yaml-list-generators-scbconnect
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
        - git:
            repoURL: https://github.com/nopponcha/argocd-devops.git
            revision: main
            files:
              - path: applicationset/scbconnect/yaml-list-generater/example1/list-elementsYaml.yaml
        - list:
            elementsYaml: |
                {{- $appsList := list }}
                {{- $projectname := index .scb | keys | first }}
                {{- range .scb.scbconnect.applications }}
                  {{- $env := .env }}
                  {{- $apps := .apps }}  
                  {{- range .clusters }}
                    {{- $cluster := .name }}
                    {{- $clustername := .clustername }}
                    {{- range $apps }}
                      {{- $name := printf "%s-%s-%s-%s" $projectname $env .name $clustername | lower }}  
                      {{- $appsList = append $appsList (dict "name" $name "projectname" $projectname "env" $env "servicename" .name "cluster" $cluster "clustername" $clustername) }}
                    {{- end }}
                  {{- end }}
                {{- end }}
                {{- toJson $appsList | nindent 2 }}
  template:
    metadata:
      name: '{{ .name }}'
    spec:
      project: default
      sources:
        - repoURL: '{{ .scb.scbconnect.common.helmRepoUrl }}'
          targetRevision: '{{ .scb.scbconnect.common.helmTargetRevision }}'
          path: '{{ .scb.scbconnect.common.chart }}'
          helm:
            valueFiles:
              - '$values/helm-value/scbconnect/{{ .servicename }}/{{ .env }}/values.yaml'
        - repoURL: '{{ .scb.scbconnect.common.helmValueRepoUrl }}'
          targetRevision: main
          ref: values
      destination:
        server: '{{ .cluster }}'
        namespace: '{{ .env }}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - DisableHelmChartCache=true
          - ApplyOutOfSyncOnly=true