apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-helm-applicationset-yaml-list-generators-ironman
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=default"]
  generators:
    - matrix:
        generators:
        - git:
            repoURL: https://github.com/nopponcha/argocd-devops.git
            revision: main
            files:
              - path: argo-cd/applicationset/ironman/yaml-list-generater/example2/list-elementsYaml.yaml
        - list:
            elementsYaml: |
                {{- $appsList := list }}
                {{- $projectname := index .scb | keys | first }}
                {{- range .scb.ironman.applications }}
                  {{- $env := .env }}
                  {{- range .clusters }}
                  {{- $cluster := .name }}
                  {{- $clustername := .clustername }}
                      {{- range .apps }}
                        {{- $name := printf "%s-%s-%s-%s" $projectname .name $clustername $env | lower }}
                        {{- $appsList = append $appsList (dict "name" $name "projectname" $projectname "env" $env "cluster" $cluster "clustername" $clustername "servicename" .name) }}
                      {{- end }}
                  {{- end }}
                {{- end }}
                {{- toJson $appsList | nindent 2 }}
  template:
    metadata:
      name: '{{ .name }}'
    spec:
      project: default
      sources:
        - repoURL: '{{ .scb.ironman.common.helmRepoUrl }}'
          targetRevision: '{{ .scb.ironman.common.helmTargetRevision }}'
          path: '{{ .scb.ironman.common.chart }}'
          helm:
            valueFiles:
              - '$values/argo-cd/helm-value/ironman/{{ .servicename }}/{{ .env }}/values.yaml'
        - repoURL: '{{ .scb.ironman.common.helmValueRepoUrl }}'
          targetRevision: main
          ref: values
      destination:
        server: '{{ .cluster }}'
        namespace: '{{ .env }}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - DisableHelmChartCache=true
          - ApplyOutOfSyncOnly=true