apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-helm-applicationset-yaml-list-generators-scbconnect
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
        - git:
            repoURL: https://github.com/nopponcha/argocd-devops.git
            revision: main
            files:
              - path: applicationset/scbconnect/yaml-list-generater/list-elementsYaml.yaml
        - list:
            elementsYaml: |
              {{- $appsList := list }}

              {{- if not .scb.scbconnect.clusters }}
                {{- fail "Error: 'clusters' not found in .scb.scbconnect" }}
              {{- end }}

              {{- range .scb.scbconnect.applications }}
                {{- $env := .env }}
                {{- range $.scb.scbconnect.clusters }}
                  {{- $cluster := . }}
                  {{- range .apps }}
                    {{- $appsList = append $appsList (dict "env" $env "name" .name "cluster" $cluster) }}
                  {{- end }}
                {{- end }}
              {{- end }}
              {{- toJson $appsList }}

  template:
    metadata:
      name: '{{ .name }}-{{ .env }}-{{ .cluster | replace "https://" "" | replace "." "-" }}'
    spec:
      project: default
      sources:
        - repoURL: '{{ .scb.scbconnect.common.helmRepoUrl }}'
          targetRevision: '{{ .scb.scbconnect.common.helmTargetRevision }}'
          path: '{{ .scb.scbconnect.common.chart }}'
          helm:
            valueFiles:
              - '$values/helm-value/scbconnect/{{ .name }}/{{ .env }}/values.yaml'
        - repoURL: '{{ .scb.scbconnect.common.helmValueRepoUrl }}'
          targetRevision: main
          ref: values
      destination:
        server: https://34.126.112.53
        namespace: '{{ .env }}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - DisableHelmChartCache=true
          - ApplyOutOfSyncOnly=true