apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-helm-applicationset-yaml-list-generators-scbconnect
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
        - git:
            repoURL: https://github.com/nopponcha/argocd-devops.git
            revision: main
            files:
              - path: applicationset/scbconnect/yaml-list-generater/list-elementsYaml.yaml
        - list:
            elements: 
              {{ .scb.scbconnect.applications | toJson }}  # ใช้ toJson เพื่อแปลงเป็น array
  template:
    metadata:
      name: '{{ .name }}-{{ .env }}'
    spec:
      project: default
      sources:
        - repoURL: '{{ .scb.scbconnect.common.helmRepoUrl }}'  # ใช้ค่า helmRepoUrl ที่กำหนดใน common
          targetRevision: '{{ .scb.scbconnect.common.helmTargetRevision }}'  # ใช้ targetRevision ที่กำหนดใน common
          path: '{{ .scb.scbconnect.common.chart }}'  # ใช้ chart ที่กำหนดใน common
          helm:
            valueFiles:
              - '$values/helm-value/scbconnect/{{ .name }}/{{ .env }}/values.yaml'
        - repoURL: '{{ .scb.scbconnect.common.helmValueRepoUrl }}'  # ใช้ helmValueRepoUrl ที่กำหนดใน common
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .env }}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - DisableHelmChartCache=true
