apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-helm-applicationset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=default"]
  generators:
    - git:
        repoURL: "https://github.com/nopponcha/argocd-devops.git"
        revision: "main"
        files:
          - path: applicationset/scbconnect/yaml-list-generater/list-elementsYaml.yaml
    - list:
        elementsYaml: '{{ .scb.scbconnect.applications | toJson }}'
  template:
    metadata:
      name: '{{ .name }}-{{ .env }}'
    spec:
      project: default
      sources:
        - repoURL: '{{ .scb.scbconnect.commonSettings.helmRepoUrl }}'
          targetRevision: '{{ .scb.scbconnect.commonSettings.helmTargetRevision }}'
          path: '{{ .chart }}'
          helm:
            valueFiles:
              - '$values/helm-value/scbconnect/{{ .name }}/{{ .env }}/values.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .env }}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - DisableHelmChartCache=true
