apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-helm-elements-json
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/nopponcha/argocd-devops.git
          revision: main
          files:
          - path: demo/applicationset/list-generater/list-elementsYaml.yaml  # Path to the JSON file in the repo
      - list:
          elements: []
          elementsYaml: "{{ .scb.scbconnect | toJson }}"  # Read the JSON file dynamically
  template:
    metadata:
      name: '{{ .name }}'
    spec:
      project: default
      sources:
        - repoURL: '{{ .helmRepoUrl }}'
          targetRevision: main
          path: '{{ .chart }}'
          helm:
            valueFiles:
              - '$values/configs/{{ .name }}/{{ .env }}/values.yaml'
        - repoURL: '{{ .helmValueRepoUrl }}'
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .name }}'
      syncPolicy:
        automated:
          prune: true