apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-helm-applicationset-yaml-list-generators-scbconnect
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
        - git:
            repoURL: https://github.com/nopponcha/argocd-devops.git
            revision: main
            files:
              - path: applicationset/scbconnect/yaml-list-generater/example2/list-elementsYaml.yaml
        - list:
            elementsYaml: |
                {{- $appsList := list }}
                {{- range .scb.scbconnect.applications }}
                  {{- $env := .env }}
                  {{- range .clusters }}
                  {{- $cluster := .name }}
                  {{- $clustername := .clustername }}
                      {{- range .apps }}
                        {{- $appsList = append $appsList (dict "env" $env "cluster" $cluster "clustername" $clustername "servicename" .name) }}
                      {{- end }}
                  {{- end }}
                {{- end }}
                {{- toJson $appsList | nindent 2 }}
  template:
    metadata:
      name: '{{ .env | lower }}-{{ .servicename | lower }}-{{ .clustername | lower }}'
    spec:
      project: default
      sources:
        - repoURL: '{{ .scb.scbconnect.common.helmRepoUrl }}'
          targetRevision: '{{ .scb.scbconnect.common.helmTargetRevision }}'
          path: '{{ .scb.scbconnect.common.chart }}'
          helm:
            valueFiles:
              - '$values/helm-value/scbconnect/{{ .servicename }}/{{ .env }}/values.yaml'
        - repoURL: '{{ .scb.scbconnect.common.helmValueRepoUrl }}'
          targetRevision: main
          ref: values
      destination:
        server: '{{ .cluster }}'
        namespace: '{{ .env }}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - DisableHelmChartCache=true
          - ApplyOutOfSyncOnly=true